'use client'

import { useMemo, useState } from 'react'
import { useSetPieces } from '@/lib/hooks/useSetPieces'
import { usePlayers } from '@/lib/hooks/usePlayers'
import type { SetPieceTaker, SetPieceTeam } from '@/lib/types'
import { SetPieceChangeAlert } from './SetPieceChangeAlert'
import { RotationRiskBadge } from '@/components/shared/RotationRiskBadge'
import { useTeamBadge } from '@/lib/hooks/useTeamBadge'
import { SetPieceViewToggle } from './SetPieceViewToggle'
import type { SetPieceView } from './SetPieceViewToggle'
import { SetPieceLeagueTable } from './SetPieceLeagueTable'

// SPQ-03 (Phase 85 D-05): tier colour map for delivery-quality badges. Defined locally \u2014
// NOT shared with TIER_CLASSES in AccuracyTab (different tier names and colour assignments).
const SP_TIER_CLASSES = {
  Elite: 'bg-green-100 text-green-800 dark:bg-green-900 dark:text-green-200',
  Good:  'bg-zinc-100 text-zinc-600 dark:bg-zinc-800 dark:text-zinc-400',
  Weak:  'bg-amber-100 text-amber-800 dark:bg-amber-900 dark:text-amber-200',
} as const

// SPQ-03 (Phase 85 D-05): "\u2014" fallback class when sp_tier is null/undefined (insufficient data).
const SP_TIER_INSUFFICIENT_CLASS = 'bg-zinc-100 text-zinc-400 dark:bg-zinc-800 dark:text-zinc-500'

// SPQ-03 (Phase 85 D-04): tooltip wording \u2014 substitutes the integer sp_sample_n.
function buildSpQualityTooltip(sampleN: number | null | undefined): string {
  const n = typeof sampleN === 'number' ? sampleN : 0
  return `xG generated by this taker's assisted set-piece shots \u2014 measures how often their deliveries produce high-xG chances (n=${n} shots)`
}

function DeliveryQualityBadge({ taker }: { taker: SetPieceTaker }) {
  const tier = taker.sp_tier ?? null
  // D-06: null/undefined sp_tier -> show "\u2014" badge with NO title attribute.
  if (tier === null) {
    return (
      <span className={`ml-2 text-xs font-normal rounded px-2 py-1 ${SP_TIER_INSUFFICIENT_CLASS}`}>
        {'\u2014'}
      </span>
    )
  }
  return (
    <span
      className={`ml-2 text-xs font-normal rounded px-2 py-1 ${SP_TIER_CLASSES[tier]}`}
      title={buildSpQualityTooltip(taker.sp_sample_n)}
    >
      {tier}
    </span>
  )
}

function TakerRow({
  label,
  taker,
  showQualityBadge,
}: {
  label: string
  taker: SetPieceTaker
  showQualityBadge?: boolean
}) {
  const name = taker.name || '\u2014'
  return (
    <p className="text-sm">
      {label}: {name}
      {taker.changed && (
        <span
          className="ml-2 text-xs font-normal rounded px-2 py-1 bg-amber-100 dark:bg-amber-900 text-amber-800 dark:text-amber-200"
          title="Taker order changed since last pipeline run"
        >
          Changed
        </span>
      )}
      {showQualityBadge && <DeliveryQualityBadge taker={taker} />}
    </p>
  )
}

function SetPieceTakerCard({
  team,
  rotationRisk,
}: {
  team: SetPieceTeam
  rotationRisk: boolean
}) {
  const { src, onError, showFallback } = useTeamBadge(team.team_short_name)
  return (
    <div className="rounded border border-zinc-200 dark:border-zinc-700 bg-white dark:bg-zinc-900 p-3 relative overflow-hidden">
      {!showFallback && src && (
        // eslint-disable-next-line @next/next/no-img-element
        <img
          src={src}
          alt=""
          aria-hidden="true"
          className="absolute bottom-0 right-0 w-14 h-14 opacity-10 pointer-events-none object-contain"
          onError={onError}
        />
      )}
      <p className="text-sm font-semibold mb-1 flex items-center gap-2">
        <span>{team.team_short_name}</span>
        <RotationRiskBadge rotationRisk={rotationRisk} />
      </p>
      <TakerRow label="Penalties" taker={team.penalty_taker} />
      <TakerRow label="Direct FK" taker={team.fk_taker} showQualityBadge />
      <TakerRow label="Corners" taker={team.corner_taker} showQualityBadge />
    </div>
  )
}

export function SetPieceTakerPanel() {
  const { data, isLoading, error } = useSetPieces()
  const { data: playersData } = usePlayers()
  const [view, setView] = useState<SetPieceView>('takers')

  // Phase 80 GWI-01 (D-04, D-16): derive team-level rotation risk by aggregating
  // any-player-on-this-team-flagged. Players with rotation_risk=true imply the
  // team has a cup/European fixture within 3 days of an upcoming PL fixture.
  const rotationRiskByTeam = useMemo(() => {
    const map: Record<number, boolean> = {}
    for (const p of playersData ?? []) {
      if (p.rotation_risk) {
        map[p.team] = true
      }
    }
    return map
  }, [playersData])

  return (
    <section className="space-y-4">
      <div>
        <h2 className="text-lg font-semibold mb-1">Set-Piece Takers</h2>
        <p className="text-sm text-zinc-500 dark:text-zinc-400 mb-4">
          Penalty, direct free kick, and corner takers per Premier League team. Sourced from FPL bootstrap-static.
        </p>
      </div>
      <SetPieceViewToggle view={view} onViewChange={setView} />

      {isLoading && (
        <p className="text-zinc-500 dark:text-zinc-400 text-center py-8">Loading set-piece data...</p>
      )}

      {error && (
        <p className="text-sm text-red-600 dark:text-red-400 py-4">
          Failed to load set-piece data. Check the pipeline output and refresh.
        </p>
      )}

      {data && data.teams.length === 0 && (
        <div>
          <p className="text-sm font-semibold text-zinc-700 dark:text-zinc-300">No set-piece data</p>
          <p className="text-sm text-zinc-500 dark:text-zinc-400">
            Set-piece taker data is not yet available. Run the pipeline to populate this panel.
          </p>
        </div>
      )}

      {data && data.teams.length > 0 && (
        <>
          {view === 'takers' && <SetPieceChangeAlert changeCount={data.change_count} />}
          {view === 'takers' ? (
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3">
              {data.teams.map((team) => (
                <SetPieceTakerCard
                  key={team.team_id}
                  team={team}
                  rotationRisk={rotationRiskByTeam[team.team_id] ?? false}
                />
              ))}
            </div>
          ) : (
            <SetPieceLeagueTable changes={data} />
          )}
        </>
      )}
    </section>
  )
}
