// @vitest-environment jsdom
// Phase 81 (SHD-01): SetPieceTakerPanel integration tests — ghost watermark crest per team card.
import { describe, it, expect, vi, beforeEach } from 'vitest'
import { render } from '@testing-library/react'

// Mock hooks BEFORE importing the component (Vitest hoisting requirement)
const mockUseSetPieces = vi.fn()
vi.mock('@/lib/hooks/useSetPieces', () => ({
  useSetPieces: () => mockUseSetPieces(),
}))
const mockUsePlayers = vi.fn()
vi.mock('@/lib/hooks/usePlayers', () => ({
  usePlayers: () => mockUsePlayers(),
}))

import { SetPieceTakerPanel } from './SetPieceTakerPanel'

const arsTeam = {
  team_id: 1,
  team_short_name: 'ARS',
  penalty_taker: { name: 'Saka', changed: false },
  fk_taker: { name: 'Odegaard', changed: false },
  corner_taker: { name: 'Saka', changed: false },
}

beforeEach(() => {
  mockUseSetPieces.mockReset()
  mockUsePlayers.mockReturnValue({ data: [], isLoading: false, error: null })
})

describe('SetPieceTakerPanel — SHD-01 ghost watermark', () => {
  it('SHD-01: card has relative and overflow-hidden classes', () => {
    mockUseSetPieces.mockReturnValue({
      data: { teams: [arsTeam], change_count: 0 },
      isLoading: false,
      error: null,
    })
    const { container } = render(<SetPieceTakerPanel />)
    const card = container.querySelector('.grid > div')!
    expect(card).not.toBeNull()
    expect(card.className).toMatch(/relative/)
    expect(card.className).toMatch(/overflow-hidden/)
  })

  it('SHD-01: ghost <img> renders with aria-hidden, opacity-10, pointer-events-none, absolute, alt=""', () => {
    mockUseSetPieces.mockReturnValue({
      data: { teams: [arsTeam], change_count: 0 },
      isLoading: false,
      error: null,
    })
    const { container } = render(<SetPieceTakerPanel />)
    const card = container.querySelector('.grid > div')!
    const ghost = card.querySelector('img[aria-hidden="true"]')
    expect(ghost).not.toBeNull()
    expect(ghost!.getAttribute('alt')).toBe('')
    expect(ghost!.className).toMatch(/opacity-10/)
    expect(ghost!.className).toMatch(/pointer-events-none/)
    expect(ghost!.className).toMatch(/absolute/)
    expect(ghost!.className).toMatch(/bottom-0/)
    expect(ghost!.className).toMatch(/right-0/)
    expect(ghost!.className).toMatch(/w-14/)
    expect(ghost!.className).toMatch(/h-14/)
  })

  it('SHD-01: unknown team renders NO ghost element (showFallback suppresses ghost)', () => {
    const unknownTeam = { ...arsTeam, team_short_name: 'XYZ' }
    mockUseSetPieces.mockReturnValue({
      data: { teams: [unknownTeam], change_count: 0 },
      isLoading: false,
      error: null,
    })
    const { container } = render(<SetPieceTakerPanel />)
    const card = container.querySelector('.grid > div')!
    expect(card.querySelector('img')).toBeNull()
    // Also verify no fallback swatch is rendered at the ghost position
    expect(card.querySelector('.rounded-full')).toBeNull()
  })
})

// ---------------------------------------------------------------------------
// SPQ-03 (Phase 85): delivery-quality tier badge tests
// ---------------------------------------------------------------------------

const TOOLTIP_PREFIX = "xG generated by this taker's assisted set-piece shots"

function makeTeam(overrides: Partial<{
  penalty: Record<string, unknown>
  fk: Record<string, unknown>
  corner: Record<string, unknown>
}> = {}) {
  return {
    team_id: 1,
    team_short_name: 'ARS',
    penalty_taker: { id: 100, name: 'Saka', changed: false, ...(overrides.penalty ?? {}) },
    fk_taker:      { id: 101, name: 'Odegaard', changed: false, ...(overrides.fk ?? {}) },
    corner_taker:  { id: 102, name: 'Saka', changed: false, ...(overrides.corner ?? {}) },
  }
}

describe('SetPieceTakerPanel — SPQ-03 delivery quality badge', () => {
  it('SPQ-03 D-01: penalty row has NO badge; FK and Corner rows DO', () => {
    const team = makeTeam({
      fk: { sp_tier: 'Elite', sp_sample_n: 14 },
      corner: { sp_tier: 'Weak', sp_sample_n: 8 },
      // penalty deliberately has no sp_tier — even if it did, badge must not render
    })
    mockUseSetPieces.mockReturnValue({ data: { teams: [team], change_count: 0 }, isLoading: false, error: null })
    const { container } = render(<SetPieceTakerPanel />)
    const rows = container.querySelectorAll('p.text-sm')
    // 4 <p> tags inside the card: header (team name) + 3 taker rows. Filter to taker rows by label text.
    const penaltyRow = Array.from(rows).find((p) => p.textContent?.startsWith('Penalties:'))!
    const fkRow = Array.from(rows).find((p) => p.textContent?.startsWith('Direct FK:'))!
    const cornerRow = Array.from(rows).find((p) => p.textContent?.startsWith('Corners:'))!
    expect(penaltyRow).toBeDefined()
    expect(fkRow).toBeDefined()
    expect(cornerRow).toBeDefined()
    // Penalty row contains zero badges (no "Changed", no quality badge)
    expect(penaltyRow.querySelectorAll('span').length).toBe(0)
    // FK row contains exactly one badge with text "Elite"
    const fkBadges = fkRow.querySelectorAll('span')
    expect(fkBadges.length).toBe(1)
    expect(fkBadges[0].textContent).toBe('Elite')
    // Corner row contains exactly one badge with text "Weak"
    const cornerBadges = cornerRow.querySelectorAll('span')
    expect(cornerBadges.length).toBe(1)
    expect(cornerBadges[0].textContent).toBe('Weak')
  })

  it('SPQ-03 SC-2 / D-04: badge title attribute equals exact D-04 wording with sp_sample_n substituted', () => {
    const team = makeTeam({ fk: { sp_tier: 'Elite', sp_sample_n: 14 } })
    mockUseSetPieces.mockReturnValue({ data: { teams: [team], change_count: 0 }, isLoading: false, error: null })
    const { container } = render(<SetPieceTakerPanel />)
    const fkRow = Array.from(container.querySelectorAll('p.text-sm')).find((p) =>
      p.textContent?.startsWith('Direct FK:'),
    )!
    const badge = fkRow.querySelector('span')!
    expect(badge.getAttribute('title')).toBe(
      "xG generated by this taker's assisted set-piece shots — measures how often their deliveries produce high-xG chances (n=14 shots)",
    )
    expect(badge.getAttribute('title')!.startsWith(TOOLTIP_PREFIX)).toBe(true)
  })

  it('SPQ-03 SC-4 / D-06: taker omitted from quality map renders "—" badge with NO title attribute', () => {
    // FK taker has no sp_tier (undefined) — simulates being absent from sp_quality.json
    const team = makeTeam({ fk: {}, corner: { sp_tier: 'Good', sp_sample_n: 9 } })
    mockUseSetPieces.mockReturnValue({ data: { teams: [team], change_count: 0 }, isLoading: false, error: null })
    // Render must not throw
    const { container } = render(<SetPieceTakerPanel />)
    const fkRow = Array.from(container.querySelectorAll('p.text-sm')).find((p) =>
      p.textContent?.startsWith('Direct FK:'),
    )!
    const badges = fkRow.querySelectorAll('span')
    expect(badges.length).toBe(1)
    expect(badges[0].textContent).toBe('—')
    // D-06: title attribute is OMITTED entirely on the "—" badge (not empty, not present)
    expect(badges[0].hasAttribute('title')).toBe(false)
  })

  it('SPQ-03 D-05: Elite uses green palette, Weak uses amber, Good uses zinc-600/zinc-400 dark variant', () => {
    const team = makeTeam({
      fk: { sp_tier: 'Elite', sp_sample_n: 14 },
      corner: { sp_tier: 'Weak', sp_sample_n: 8 },
    })
    mockUseSetPieces.mockReturnValue({ data: { teams: [team], change_count: 0 }, isLoading: false, error: null })
    const { container } = render(<SetPieceTakerPanel />)
    const fkBadge = Array.from(container.querySelectorAll('p.text-sm'))
      .find((p) => p.textContent?.startsWith('Direct FK:'))!
      .querySelector('span')!
    const cornerBadge = Array.from(container.querySelectorAll('p.text-sm'))
      .find((p) => p.textContent?.startsWith('Corners:'))!
      .querySelector('span')!
    // Elite -> green palette
    expect(fkBadge.className).toMatch(/bg-green-100/)
    expect(fkBadge.className).toMatch(/text-green-800/)
    expect(fkBadge.className).toMatch(/dark:bg-green-900/)
    expect(fkBadge.className).toMatch(/dark:text-green-200/)
    // Weak -> amber palette
    expect(cornerBadge.className).toMatch(/bg-amber-100/)
    expect(cornerBadge.className).toMatch(/text-amber-800/)
    // And the inline-badge class pattern (matches existing "Changed" badge convention)
    expect(fkBadge.className).toMatch(/ml-2 text-xs font-normal rounded px-2 py-1/)
  })

  it('SPQ-03 D-05: "—" badge uses the lighter zinc-100/zinc-400 + dark zinc-800/zinc-500 class', () => {
    const team = makeTeam({ fk: {}, corner: { sp_tier: null } })
    mockUseSetPieces.mockReturnValue({ data: { teams: [team], change_count: 0 }, isLoading: false, error: null })
    const { container } = render(<SetPieceTakerPanel />)
    const fkBadge = Array.from(container.querySelectorAll('p.text-sm'))
      .find((p) => p.textContent?.startsWith('Direct FK:'))!
      .querySelector('span')!
    expect(fkBadge.textContent).toBe('—')
    expect(fkBadge.className).toMatch(/bg-zinc-100/)
    expect(fkBadge.className).toMatch(/text-zinc-400/)
    expect(fkBadge.className).toMatch(/dark:bg-zinc-800/)
    expect(fkBadge.className).toMatch(/dark:text-zinc-500/)
  })
})
