'use client'

import { useMemo, useState } from 'react'
import { useSetPieces } from '@/lib/hooks/useSetPieces'
import { usePlayers } from '@/lib/hooks/usePlayers'
import type { SetPieceTaker, SetPieceTeam } from '@/lib/types'
import { SetPieceChangeAlert } from './SetPieceChangeAlert'
import { RotationRiskBadge } from '@/components/shared/RotationRiskBadge'
import { useTeamBadge } from '@/lib/hooks/useTeamBadge'
import { SetPieceViewToggle } from './SetPieceViewToggle'
import type { SetPieceView } from './SetPieceViewToggle'
import { SetPieceLeagueTable } from './SetPieceLeagueTable'
import { Card } from '@/components/ui/Card'
import { Chip } from '@/components/ui/Chip'

// SPQ-03 (Phase 85 D-05) tier → Chip intent. UIX-03 Task 4: collapsed into Chip
// per the badge policy — Elite→positive, Good→neutral, Weak→warning.
const SP_TIER_INTENT = { Elite: 'positive', Good: 'neutral', Weak: 'warning' } as const

// SPQ-03 (Phase 85 D-04): tooltip wording — substitutes the integer sp_sample_n.
function buildSpQualityTooltip(sampleN: number | null | undefined): string {
  const n = typeof sampleN === 'number' ? sampleN : 0
  return `xG generated by this taker's assisted set-piece shots — measures how often their deliveries produce high-xG chances (n=${n} shots)`
}

function DeliveryQualityBadge({ taker }: { taker: SetPieceTaker }) {
  const tier = taker.sp_tier ?? null
  // D-06: null/undefined sp_tier -> show "—" chip with NO title attribute.
  if (tier === null) {
    return <Chip size="sm">{'—'}</Chip>
  }
  return (
    <Chip size="sm" intent={SP_TIER_INTENT[tier]} title={buildSpQualityTooltip(taker.sp_sample_n)}>
      {tier}
    </Chip>
  )
}

function TakerRow({
  label,
  taker,
  showQualityBadge,
}: {
  label: string
  taker: SetPieceTaker
  showQualityBadge?: boolean
}) {
  const name = taker.name || '—'
  return (
    <p className="text-sm flex flex-wrap items-center gap-2">
      {label}: {name}
      {taker.changed && (
        <Chip intent="warning" size="sm" title="Taker order changed since last pipeline run">
          Changed
        </Chip>
      )}
      {showQualityBadge && <DeliveryQualityBadge taker={taker} />}
    </p>
  )
}

function SetPieceTakerCard({
  team,
  rotationRisk,
}: {
  team: SetPieceTeam
  rotationRisk: boolean
}) {
  const { src, onError, showFallback } = useTeamBadge(team.team_short_name)
  return (
    // UIX-03 Task 4: Card primitive; the ghost-watermark positioning frame
    // (relative + overflow-hidden, SHD-01) lives on the inner padded div.
    <Card padding="none">
      <div className="relative overflow-hidden rounded-lg p-3">
        {!showFallback && src && (
          // eslint-disable-next-line @next/next/no-img-element
          <img
            src={src}
            alt=""
            aria-hidden="true"
            className="absolute bottom-0 right-0 w-14 h-14 opacity-10 pointer-events-none object-contain"
            onError={onError}
          />
        )}
        <p className="text-sm font-semibold mb-1 flex items-center gap-2">
          <span>{team.team_short_name}</span>
          <RotationRiskBadge rotationRisk={rotationRisk} />
        </p>
        <TakerRow label="Penalties" taker={team.penalty_taker} />
        <TakerRow label="Direct FK" taker={team.fk_taker} showQualityBadge />
        <TakerRow label="Corners" taker={team.corner_taker} showQualityBadge />
      </div>
    </Card>
  )
}

export function SetPieceTakerPanel() {
  const { data, isLoading, error } = useSetPieces()
  const { data: playersData } = usePlayers()
  const [view, setView] = useState<SetPieceView>('takers')

  // Phase 80 GWI-01 (D-04, D-16): derive team-level rotation risk by aggregating
  // any-player-on-this-team-flagged. Players with rotation_risk=true imply the
  // team has a cup/European fixture within 3 days of an upcoming PL fixture.
  const rotationRiskByTeam = useMemo(() => {
    const map: Record<number, boolean> = {}
    for (const p of playersData ?? []) {
      if (p.rotation_risk) {
        map[p.team] = true
      }
    }
    return map
  }, [playersData])

  return (
    <section className="space-y-4">
      <div>
        <h2 className="text-lg font-semibold mb-1">Set-Piece Takers</h2>
        <p className="text-sm text-ink-muted mb-4">
          Penalty, direct free kick, and corner takers per Premier League team. Sourced from FPL bootstrap-static.
        </p>
      </div>
      {/* Always visible — change alert belongs to the panel, not to a specific view */}
      {data && data.teams.length > 0 && (
        <SetPieceChangeAlert changeCount={data.change_count} />
      )}
      <SetPieceViewToggle view={view} onViewChange={setView} />

      {isLoading && (
        <p className="text-ink-muted text-center py-8">Loading set-piece data...</p>
      )}

      {error && (
        <p className="text-sm text-negative py-4">
          Failed to load set-piece data. Check the pipeline output and refresh.
        </p>
      )}

      {data && data.teams.length === 0 && (
        <div>
          <p className="text-sm font-semibold">No set-piece data</p>
          <p className="text-sm text-ink-muted">
            Set-piece taker data is not yet available. Run the pipeline to populate this panel.
          </p>
        </div>
      )}

      {data && data.teams.length > 0 && (
        <>
          {view === 'takers' ? (
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3">
              {data.teams.map((team) => (
                <SetPieceTakerCard
                  key={team.team_id}
                  team={team}
                  rotationRisk={rotationRiskByTeam[team.team_id] ?? false}
                />
              ))}
            </div>
          ) : (
            <SetPieceLeagueTable changes={data} />
          )}
        </>
      )}
    </section>
  )
}
